### ISSUE TITLE
Visualisation de l'évolution de la pêche

### ISSUE THREAD

**Issue by robindemourat** [medialab/portic-datasprint-2022#13]
https://docs.google.com/document/d/1YtuKf4hgk9UJiekNcVa_vK2MGYYgvopOVTuZeHfyopU/edit?disco=AAAAX2m_zKg

Silvia:

> un graphique à barre superposée des différents types de pêche ferait l'affaire

Données: https://docs.google.com/spreadsheets/d/1i1iOgXdW8vp8NG5SD9m1rrz5WyUXpFHj/edit#gid=351410703

Première vue sur le design:

- années sur les X, valeur sur les Y
- stacké par type de pêche

**Comment by Myllaume** [comment]
La viz a été réalisée : https://github.com/medialab/portic-storymaps-2022/commit/d460ed0eec0c4fd89871b0b6cdc6b3b61f5df712
